//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace knockoutJsTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamesTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public string Desc { get; set; }
        public int Rating { get; set; }
        public bool Completed { get; set; }
        public decimal PPH { get; set; }
    }
}
